#################
# CONFIGURATION #
#################

# iPixel-ESPHome ESPHome Configuration
esphome:
  name: ipixel-esphome
  friendly_name: ipixel-ESPHome

# Configure the ESP32 platform
esp32:
  board: "{{BOARD}}"
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "30"

# Enable logging
logger:
  level: VERBOSE  # or VERY_VERBOSE for maximum detail

captive_portal:
